[package]
name = "uiux-standard-desktop"
version = "0.1.0"
description = "UI/UX Standard Desktop Application"
authors = ["ITAnalytics"]
edition = "2021"

[lib]
name = "uiux_standard_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
